services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: norff/docker-project-frontend:latest
    container_name: app-frontend
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: norff/docker-project-backend:latest
    container_name: app-backend
    #cap_drop:
    #  - all
    #security_opt:
    #  - no-new-privileges:true
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - PORT=8081
    healthcheck:
      #test: /usr/local/bin/healthcheck http://localhost:8081/health || exit 1
      test: ["CMD", "wget", "--no-check-certificate", "-qO-", "http://localhost:8081/health"]
      #test: ["CMD", "cat", "/etc/os-release"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

# ==================== VOLUMES ====================
#volumes: