services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: norff/docker-project-frontend:latest
    container_name: app-frontend
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: norff/docker-project-backend:latest
    container_name: app-backend
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

# ==================== VOLUMES ====================
#volumes: