services:

  # ==================== FRONTEND ====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: norff/docker-project-frontend:latest
    container_name: app-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - VUE_APP_API_URL=http://backend:8081
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'Frontend health check OK' && exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # ==================== BACKEND ====================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: norff/docker-project-backend:latest
    container_name: app-backend
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# ==================== NETWORKS ====================
networks:
  app-network:
    driver: bridge

# ==================== VOLUMES ====================
#volumes: