services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/docker-project-frontend:latest
    container_name: app-frontend
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
    networks:
      - public-network
      - internal-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/docker-project-backend:latest
    container_name: app-backend
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    ports:
      - "8081:8081"
    networks:
      - internal-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  public-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true
