name: Docker Project Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Install Hadolint
          run: |
            curl -L https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64  > /usr/local/bin/hadolint
            chmod +x /usr/local/bin/hadolint

        - name: Run Hadolint for Backend
          run: |
            hadolint backend/Dockerfile

        - name: Run Hadolint for Frontend
          run: |
            hadolint frontend/Dockerfile

        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest

        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest


        - name: Scan Backend Image with Trivy
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
            format: table
            exit-code: "0"
            vuln-type: os,library

        - name: Scan Frontend Image with Trivy
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
            format: table
            exit-code: "0"
            vuln-type: os,library

        - name: Generate SBOM for Backend with Syft
          uses: anchore/sbom-action@v0
          with:
            image: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
            output: sbom-backend.json

        - name: Generate SBOM for Frontend with Syft
          uses: anchore/sbom-action@v0
          with:
            image: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
            output: sbom-frontend.json

        - name: Upload SBOM files
          uses: actions/upload-artifact@v3
          with:
            name: sboms
            path: |
              sbom-backend.json
              sbom-frontend.json

  run-with-docker-compose:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build via Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0